Update wercker.yml

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -6,12 +6,12 @@ box:
   ports:
     - "5000"
 
-dev:
-  steps:
-    - pip-install
-    - internal/watch:
-        code: python app.py
-        reload: true
+#dev:
+#  steps:
+#    - pip-install
+#    - internal/watch:
+#        code: python app.py
+#        reload: true
         
 # Build definition
 build:
@@ -27,16 +27,32 @@ build:
           python app_test.py
           echo "python version $(python --version) running"
           echo "pip version $(pip --version) running" 
-#Build docker container
+
+#Build docker and test docker container. Push to OCIR if test is passed
 docker-build:
   steps:
     - internal/docker-build:
       dockerfile: Dockerfile 
       image-name: cities-demo
- 
-#Push release definition
-#push-release:
- # steps:
+    - internal/docker-run:
+        image: cities-demo
+        name: TestContainer     
+    - script: 
+        name: Test the container
+        code: |
+            if curlOutput=`curl -s TestContainer:5000`; then 
+                if [ "$curlOutput" == "Hello World!" ]; then
+                    echo "Test passed: container gave expected response"
+                else
+                    echo "Test failed: container gave unexpected response: " $curlOutput
+                    exit 1
+                fi   
+            else 
+                echo "Test failed: container did not respond"
+                exit 1
+            fi        
+    - internal/docker-kill:
+        name: TestContainer   
     - internal/docker-push:
        image-name: cities-demo
        username: $OCIRUSERNAME
@@ -45,8 +61,7 @@ docker-build:
        #tag: ${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        repository: fra.ocir.io/ptsbm02/devops
        registry: https://fra.ocir.io/v2
-       #working-dir: /pipeline/source
-       
+       #working-dir: /pipeline/source  
 inject-secret:
     box:
         id: alpine
@@ -65,7 +80,7 @@ inject-secret:
         insecure-skip-tls-verify: true
         command: create secret docker-registry ptsbm02 --docker-server=$DOCKER_REGISTRY --docker-username=$OCIRUSERNAME --docker-password=$SECRET_TOKEN --docker-email=$DOCKER_EMAIL; echo create registry secret       
 
-deploy-to-stage:
+deploy-to-oke:
     box:
         id: alpine
         cmd: /bin/sh
@@ -84,19 +99,19 @@ deploy-to-stage:
         token: $KUBERNETES_TOKEN
         #namespace: stage
         insecure-skip-tls-verify: true
-        command: apply -f kubernetes.yml --namespace=stage
-    - script:
-        name: "Get Load Balancer config"
-        code: |
-          export FRONTEND_SERVICE_IP=$(kubectl get -o jsonpath="{.status.loadBalancer.ingress[0].ip}"  --namespace=stage service sample-app-backend-svc)
-          echo $FRONTEND_SERVICE_IP
-    after-steps:
-    - wercker/email-notify@2.0.1:
-        from: wercker@devopsdemo.com
-        to: radu.dobrinescu@oracle.com
-        username: $SMTPUSER
-        password: $SMTPPASS
-        host: $SMTPSERVER
-        branch: master
-        passed-body: Passed body
-        failed-body: Failed body
+        command: apply -f kubernetes.yml
+    #- script:
+    #    name: "Get Load Balancer config"
+    #    code: |
+    #      export FRONTEND_SERVICE_IP=$(kubectl get -o jsonpath="{.status.loadBalancer.ingress[0].ip}"  --namespace=stage service sample-app-backend-svc)
+    #      echo $FRONTEND_SERVICE_IP
+    #after-steps:
+    #- wercker/email-notify@2.0.1:
+    #    from: wercker@devopsdemo.com
+    #    to: radu.dobrinescu@oracle.com
+    #    username: $SMTPUSER
+    #    password: $SMTPPASS
+    #    host: $SMTPSERVER
+    #    branch: master
+    #    passed-body: Passed body
+    #    failed-body: Failed body
